### ISSUE TITLE
Treat Filters as IConstraint

### ISSUE THREAD

**Issue by jplindgren** [ailtonguitar/rules4net#9]
If we treat filters as IConstraint and the Constraints itself as a leaf node, we can let the user create complex conditions like a tree.

Conditions would be composable like that.
```
var filter = OrFilter(new AndFilter(..list of constraints..), 
                                       new AndFilter(..another list of contraints..));```

**Comment by ailtonguitar** [comment]
This issue is closed with "Turn filter into a constraint " pull request.
